In [30]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [31]:
data = np.array([3, 4, 5, 6, 6, 2, 2, 1, 5, 8])
data.dtype

dtype('int64')

In [32]:
data = np.array([[1, 2, 3], [4, 5, 6]])
print('次元数:', data.ndim)
print('各次元のサイズ:', data.shape)
print('全要素数:', data.size)

次元数: 2
各次元のサイズ: (2, 3)
全要素数: 6


In [33]:
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([1, 2, 3, 4, 5])
print('2倍:', data1 * 2)
print('掛け算:', data1 * data2)
print('割り算:', data1 / data2)
print('累乗:', data1 ** 2)

2倍: [ 2  4  6  8 10]
掛け算: [ 1  4  9 16 25]
割り算: [1. 1. 1. 1. 1.]
累乗: [ 1  4  9 16 25]


In [34]:
data = np.array([3, 4, 5, 6, 6, 2, 2, 1, 5, 8])
data.sort()
print(data)

data[::-1].sort()
print(data)

[1 2 2 3 4 5 5 6 6 8]
[8 6 6 5 5 4 3 2 2 1]


In [35]:
data = np.array([1, 2, 3, 4, 5])
print('Min:', data.min())
print('Max:', data.max())
print('Sum:', data.sum())
print('積み上げていった結果の配列:', data.cumsum())

Min: 1
Max: 5
Sum: 15
積み上げていった結果の配列: [ 1  3  6 10 15]


In [40]:
random.seed(0)

random_data = random.randn(10)
print(random_data)

[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]
